### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by solidnerd** [ssddanbrown/BookStack#102]
Hey, 
i would like to know if some plans to dockerize the application. I searched for it but i found nothing on the issue's and pr's. A cool guy made an dockerized version of bookstack but it seems to be outdated. I made a fork of it and refactored it to the latest docker related stuff. If you want to see it check it out under [docker preview](https://github.com/SolidNerd/docker-bookstack/tree/master). 

Let me know what you think about it.

**Comment by senthai** [comment]
i like the idea! but i tried to install it on my webspace and it does not work. first i get an error 137 and when i start the composer again it just says: whooops something went wrong ;)

**Comment by SolidNerd** [comment]
Okay, the current problem is that image is not the correct one. I could publish it on Docker Hub later than it will work.

**Comment by senthai** [comment]
ah nice.... thx for the effort!

**Comment by SolidNerd** [comment]
I updated the branch and now should everything work. Let know if you get any issues.

**Comment by senthai** [comment]
I tried again and now i got an error 1 for the image. do i have to update the docker-composer.yml?

**Comment by SolidNerd** [comment]
Yes. Your docker-compose.yml need to be look like this:

```
version: '2'
services:
  bookstack:
    image: solidnerd/bookstack
    depends_on:
      - db
    environment:
    - DB_HOST=db
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    ports:
    - "8080:80"
  db:
    image: mysql:5.7.12
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
```

**Comment by senthai** [comment]
now it looks good... thx!

**Comment by SolidNerd** [comment]
You are welcome !

**Comment by ssddanbrown** [comment]
This is awesome :smiley:, Thanks @SolidNerd and also thanks @Kilhog. 

I did try it yesterday but ran into the errors mentioned above, The new version worked perfectly though. It's awesome to see it just work. I've tried to create this before, If only to help my testing, but I ran into issues so thank you so much.

I've not had any plans to create an 'official' docker image just yet as I don't feel comfortable enough with docker to ensure correct configuration and security (Since I've only used it for a short time) but it is something I'd like to see.  I'm fully happy to support people creating docker scripts like this though.

**Comment by senthai** [comment]
hey @SolidNerd.
I am frequently running into the "whooops" issue.
Any Idea what I did wrong?
I changed the docker-compose.yml to this:

`version: '2'
services:
  bookstack:
    image: solidnerd/bookstack
    depends_on:
      - db
    environment:
    - DB_HOST=db
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=myownpassword
    ports:
    - "7070:80"
  db:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=myownrootpw
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=myownpassword
`
do i HAVE to use the mysql version you suggest? (even when i use the version tag it run into that error)

thx!

**Comment by SolidNerd** [comment]
I tested your configuration and it's working for me.  Do you have the latest image from me. When not try `docker pull solidnerd/bookstack`. After that isn't working could you provide me more information about your docker setup with the following commands.  `docker-compose --version` and 'docker info'.

**Comment by senthai** [comment]
hi... thx for your answer!
it is strange :sa: 
I see the loginscreen, but when I login it shows the "whoops" error (btw... funny name)

My docker-compose versions is the latest (as far as i know):
docker-compose version 1.6.2, build 4d72027

docker info

> Containers: 8
>  Running: 7
>  Paused: 0
>  Stopped: 1
> Images: 42
> Server Version: 1.11.0
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 202
>  Dirperm1 Supported: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins: 
>  Volume: local
>  Network: bridge null host
> Kernel Version: 3.16.0-4-amd64
> Operating System: Debian GNU/Linux 8 (jessie)
> OSType: linux
> Architecture: x86_64
> CPUs: 8
> Total Memory: 23.6 GiB
> Name: bla.domain.yeah
> ID: SOMEID
> Docker Root Dir: /var/lib/docker
> Debug mode (client): false
> Debug mode (server): false
> Registry: https://index.docker.io/v1/
> WARNING: No memory limit support
> WARNING: No swap limit support
> WARNING: No kernel memory limit support
> WARNING: No oom kill disable support
> WARNING: No cpu cfs quota support
> WARNING: No cpu cfs period support

many warnings????? :dancer:

**Comment by SolidNerd** [comment]
Okay. The latest `docker-compose` version is `1.7.0`. You could upgrade it and try it again. I will test it under a debian but this takes some time. I will give you feedback about the tests later.

**Comment by senthai** [comment]
hm... i am using the ppa from docker in debian. but cannot get an update :(

**Comment by SolidNerd** [comment]
So, i guess that i could figured out a bug of the container, but this need more time to fix it. It has something todo with waiting step for the db. I updated your docker-compose file and for me its working under debian:
```
version: '2'
services:
  bookstack:
    image: solidnerd/bookstack
    restart: always
    depends_on:
      - db
    environment:
    - DB_HOST=db
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=myownpassword
    ports:
    - "7070:80"
    networks:
    - backend
  db:
    image: mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=myownrootpw
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=myownpassword
    volumes:
    - ./mysql:/var/lib/mysql
    networks:
    - backend

networks:
 backend:
```

It contains serveral changes. 

1. Both Containers will every time restart if they exited and when you restart your docker daemon they will restart aswell. I guess this will fix the "bug".
2. I added a volume for the db. This should bring performance and persistence.
3. Last step  I replaced the network. `docker-compose` creates by default a network but this seems not working at the time for this setup. 

Before you run `docker-compose up` please remove all old stuff. I hope i could help you. I will update my docker-compose file later.
